"""Release tiers and license bundle for a converted LeRobot dataset.

One LeRobot dataset = one source dataset = one licence. The *tier* decides what may leave the
building and shapes the conversion:

    open         full dataset (video + labels), redistributable under ``derived_license``
    gated        same content as ``open``, but published behind an access gate (e.g. HF gated repo)
    labels_only  no pixels: video stream dropped, plus a rehydration index (meta/source_frames.parquet)
    internal     never distributed; converted for in-house training only, README carries a banner

:func:`write_release_bundle` writes ``LICENSES/<source>/``, ``meta/release.json`` and a root
``README.md`` that states provenance, licence obligations and the modifications we made.
:func:`check_release_consistency` catches configuration that would violate the source licence
(labels-only job that still exports video, ShareAlike source released under a different licence, ...).
"""

from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path

RELEASE_TIERS = ("open", "gated", "labels_only", "internal")
RELEASE_JSON = "meta/release.json"
LICENSES_DIR = "LICENSES"

# SPDX id -> (canonical URL, short human summary of the obligations that matter for a derived dataset)
KNOWN_LICENSES: dict[str, dict] = {
    "Apache-2.0": {
        "url": "https://www.apache.org/licenses/LICENSE-2.0",
        "obligations": "Keep the licence text, copyright and NOTICE content; state that the data was modified; do not use the authors' trademarks.",
        "family": "permissive",
    },
    "MIT": {
        "url": "https://opensource.org/license/mit",
        "obligations": "Keep the licence text and copyright notice.",
        "family": "permissive",
    },
    "CDLA-Permissive-2.0": {
        "url": "https://cdla.dev/permissive-2-0/",
        "obligations": "Include the CDLA-Permissive-2.0 text with any redistribution of the data; results derived from the data carry no obligation.",
        "family": "permissive",
    },
    "CC-BY-4.0": {
        "url": "https://creativecommons.org/licenses/by/4.0/",
        "obligations": "Attribution: name the source, link the licence, state the modifications.",
        "family": "attribution",
    },
    "CC-BY-SA-4.0": {
        "url": "https://creativecommons.org/licenses/by-sa/4.0/",
        "obligations": "Attribution as CC-BY, and the derived dataset must be released under CC-BY-SA-4.0 (ShareAlike).",
        "family": "sharealike",
    },
    "CC-BY-NC-4.0": {
        "url": "https://creativecommons.org/licenses/by-nc/4.0/",
        "obligations": "Attribution as CC-BY; non-commercial use only, the derived dataset must stay non-commercial.",
        "family": "noncommercial",
    },
    "CC-BY-NC-SA-4.0": {
        "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
        "obligations": "Attribution; non-commercial only; the derived dataset must be released under CC-BY-NC-SA-4.0.",
        "family": "noncommercial_sharealike",
    },
}

DEFAULT_DERIVED_LICENSE = {
    "permissive": "CC-BY-4.0",
    "attribution": "CC-BY-4.0",
    "sharealike": "CC-BY-SA-4.0",
    "noncommercial": "CC-BY-NC-4.0",
    "noncommercial_sharealike": "CC-BY-NC-SA-4.0",
}

MODIFICATIONS = [
    "Frames resampled to a fixed frame rate and clipped into episodes by the EgoSmith pipeline.",
    "Hand poses (wrist pose, fingertips, MANO parameters) are estimates produced by the EgoSmith pipeline from the RGB frames, not ground truth from the source dataset, unless the source shipped native hand annotations (see notes).",
    "Camera poses come from monocular SLAM run by the pipeline; language instructions were generated by the annotation stage.",
    "Values are repacked into the LeRobot v3.0 layout described in meta/info.json.",
]


@dataclass
class ReleaseSpec:
    tier: str = "internal"
    source_name: str = ""  # human name of the source dataset, e.g. "TACO"
    source_url: str = ""  # project / download page
    license: str = "custom"  # SPDX id from KNOWN_LICENSES or "custom"
    license_url: str = ""  # required when license == "custom" (or to override the canonical URL)
    license_file: str | None = None  # path to the licence / terms text; copied into LICENSES/<source>/
    license_text: str | None = None  # inline alternative to license_file
    derived_license: str | None = None  # licence of OUR dataset; default derived from the source family
    copyright: str = ""  # copyright / attribution line required by the source
    citation: str = ""  # bibtex or free text
    notes: str = ""  # anything special: "gate registers contact info only", "hand data from native annotations", ...
    uses_native_hand_annotations: bool = False  # True when lowdim/mano came from the source's own hand labels
    contact: str = ""  # who to ask about this release

    def validate(self) -> list[str]:
        problems = []
        if self.tier not in RELEASE_TIERS:
            problems.append(f"tier {self.tier!r} not in {RELEASE_TIERS}")
        if self.tier != "internal":
            if not self.source_name:
                problems.append("source_name is required for a distributable tier")
            if self.license == "custom" and not (self.license_file or self.license_text):
                problems.append("custom licence needs license_file or license_text (the full terms must ship with the data)")
            if self.license_file and not Path(self.license_file).is_file():
                problems.append(f"license_file not found: {self.license_file}")
            if self.license not in KNOWN_LICENSES and self.license != "custom":
                problems.append(f"unknown licence id {self.license!r}; use one of {sorted(KNOWN_LICENSES)} or 'custom'")
        return problems

    @property
    def family(self) -> str:
        return KNOWN_LICENSES.get(self.license, {}).get("family", "custom")

    @property
    def effective_derived_license(self) -> str:
        if self.derived_license:
            return self.derived_license
        return DEFAULT_DERIVED_LICENSE.get(self.family, "custom")


def release_spec_from_dict(raw: dict | None) -> ReleaseSpec:
    raw = dict(raw or {})
    allowed = set(ReleaseSpec.__dataclass_fields__)
    unknown = sorted(set(raw) - allowed)
    if unknown:
        raise ValueError(f"release: unknown keys {unknown}; allowed: {sorted(allowed)}")
    return ReleaseSpec(**raw)


def check_release_consistency(spec: ReleaseSpec, *, include_video: bool, has_source_frames: bool) -> list[str]:
    """Configuration errors that would breach the source licence or make the release unusable."""
    problems = spec.validate()
    if spec.tier == "labels_only":
        if include_video:
            problems.append("labels_only tier must not export video (set converter.include_video: false)")
        if not has_source_frames:
            # meta/source_frames.parquet (the index rehydration consumes) is written only from descriptor_manifest;
            # a source_map alone yields meta/source_map.parquet, which the release/rehydrate path does not read.
            problems.append("labels_only tier needs the rehydration index meta/source_frames.parquet: pass descriptor_manifest (source_map alone does not produce it)")
    if spec.tier in ("open", "gated"):
        fam = spec.family
        derived = spec.effective_derived_license
        if fam == "sharealike" and derived != "CC-BY-SA-4.0":
            problems.append(f"source is ShareAlike; derived_license must be CC-BY-SA-4.0, got {derived}")
        if fam == "noncommercial" and derived not in ("CC-BY-NC-4.0", "CC-BY-NC-SA-4.0"):
            problems.append(f"source is NonCommercial; derived_license must be CC-BY-NC-4.0 (or NC-SA), got {derived}")
        if fam == "noncommercial_sharealike" and derived != "CC-BY-NC-SA-4.0":
            problems.append(f"source is NC-ShareAlike; derived_license must be CC-BY-NC-SA-4.0, got {derived}")
    return problems


BUNDLED_LICENSE_DIR = Path(__file__).resolve().parent / "licenses"


def bundled_license_text(license_id: str) -> str | None:
    """Canonical SPDX text shipped with the repo for the standard licences (Apache-2.0, MIT, CDLA, CC-*)."""
    path = BUNDLED_LICENSE_DIR / f"{license_id}.txt"
    return path.read_text(encoding="utf-8") if path.exists() else None


def _license_text(spec: ReleaseSpec) -> str | None:
    if spec.license_text:
        return spec.license_text
    if spec.license_file:
        return Path(spec.license_file).read_text(encoding="utf-8")
    return bundled_license_text(spec.license)


def _slug(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in name.strip()) or "source"


def write_release_bundle(root: str, spec: ReleaseSpec, *, conversion_summary: dict | None = None) -> dict:
    """Write LICENSES/, meta/release.json and README.md. Returns the release.json payload."""
    root_path = Path(root)
    info = json.loads((root_path / "meta" / "info.json").read_text(encoding="utf-8"))
    provenance_path = root_path / "meta" / "egosmith_provenance.json"
    provenance = json.loads(provenance_path.read_text(encoding="utf-8")) if provenance_path.exists() else {}
    has_video = bool(info.get("video_path"))
    source_frames = provenance.get("source_frames_index")

    lic_dir = root_path / LICENSES_DIR / _slug(spec.source_name or "source")
    if spec.tier != "internal":
        lic_dir.mkdir(parents=True, exist_ok=True)
        text = _license_text(spec)
        if text is not None:
            (lic_dir / "LICENSE.txt").write_text(text, encoding="utf-8")
        else:
            url = spec.license_url or KNOWN_LICENSES.get(spec.license, {}).get("url", "")
            (lic_dir / "LICENSE.txt").write_text(f"{spec.license}\n{url}\n", encoding="utf-8")
        notice_lines = [f"Source dataset: {spec.source_name}", f"URL: {spec.source_url}", f"Licence: {spec.license} {spec.license_url or KNOWN_LICENSES.get(spec.license, {}).get('url', '')}"]
        if spec.copyright:
            notice_lines += ["", spec.copyright]
        if spec.citation:
            notice_lines += ["", "Citation:", spec.citation]
        if spec.notes:
            notice_lines += ["", "Notes:", spec.notes]
        (lic_dir / "NOTICE.txt").write_text("\n".join(notice_lines) + "\n", encoding="utf-8")
    elif (root_path / LICENSES_DIR).exists():
        shutil.rmtree(root_path / LICENSES_DIR)

    payload = {
        **asdict(spec),
        "derived_license": spec.effective_derived_license,
        "license_family": spec.family,
        "has_video": has_video,
        "source_frames_index": source_frames,
        "distributable": spec.tier in ("open", "gated", "labels_only"),
        "conversion": conversion_summary,
    }
    payload.pop("license_text", None)
    # release.json ships with the dataset: reduce local absolute paths (license_file, conversion.output_dir,
    # conversion.source_mapping.map, ...) to base names
    from lib.pipeline.exporters.lerobot_export import _shareable_index_issues, shareable_paths

    if isinstance(conversion_summary, dict) and isinstance(conversion_summary.get("index_issues"), dict):
        # an unreadable shard's error text may embed local paths (same reduction as the provenance)
        payload["conversion"] = {**conversion_summary, "index_issues": _shareable_index_issues(conversion_summary["index_issues"])}
    payload = shareable_paths(payload)
    (root_path / RELEASE_JSON).parent.mkdir(parents=True, exist_ok=True)
    (root_path / RELEASE_JSON).write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (root_path / "README.md").write_text(render_readme(spec, info, provenance, payload), encoding="utf-8")
    return payload


def render_readme(spec: ReleaseSpec, info: dict, provenance: dict, payload: dict) -> str:
    name = spec.source_name or Path(info.get("robot_type", "dataset")).name
    lines = [f"# EgoSmith LeRobot export: {name}", ""]
    if spec.tier == "internal":
        lines += ["> **INTERNAL ONLY. DO NOT DISTRIBUTE.** The source dataset's terms do not allow redistribution of the data or of derived annotations.", ""]
    elif spec.tier == "labels_only":
        lines += ["> **Labels only.** This release contains no images or video. Pixels must be obtained from the source dataset under its own terms and re-attached with `scripts/build/lerobot_rehydrate_video.py` using `meta/source_frames.parquet`.", ""]
    elif spec.tier == "gated":
        lines += ["> Published behind an access gate; downloaders accept the source dataset's terms listed below.", ""]

    lines += ["## Provenance", "", "| | |", "|---|---|", f"| source dataset | {spec.source_name} |", f"| source URL | {spec.source_url} |",
              f"| source licence | {spec.license} ({spec.license_url or KNOWN_LICENSES.get(spec.license, {}).get('url', '')}) |",
              f"| this dataset's licence | {payload['derived_license']} |", f"| release tier | {spec.tier} |",
              f"| LeRobot codebase version | {info.get('codebase_version')} |", f"| episodes / frames | {info.get('total_episodes')} / {info.get('total_frames')} |",
              f"| fps | {info.get('fps')} |", f"| video stream | {'yes (h264)' if payload['has_video'] else 'none'} |", ""]
    obligations = KNOWN_LICENSES.get(spec.license, {}).get("obligations")
    if obligations or spec.notes:
        lines += ["## Licence obligations", ""]
        if obligations:
            lines.append(f"- {obligations}")
        if spec.notes:
            lines.append(f"- {spec.notes}")
        if spec.copyright:
            lines.append(f"- Copyright notice: {spec.copyright}")
        lines.append(f"- Full text: `LICENSES/{_slug(spec.source_name or 'source')}/LICENSE.txt`")
        lines.append("")
    lines += ["## Modifications relative to the source", ""] + [f"- {m}" for m in MODIFICATIONS]
    if spec.uses_native_hand_annotations:
        lines.append("- Hand values in this dataset are derived from the source dataset's own hand annotations (native features), so they inherit that data's licence.")
    lines += ["", "## Layout", "", "```", "meta/info.json  meta/stats.json  meta/tasks.parquet  meta/episodes/  meta/release.json  meta/egosmith_provenance.json",
              "data/chunk-XXX/file-XXX.parquet" + ("", "  videos/observation.images.head/chunk-XXX/file-XXX.mp4")[payload["has_video"]], "```", ""]
    feats = info.get("features", {})
    lines += ["| feature | dtype | shape |", "|---|---|---|"] + [f"| `{k}` | {v.get('dtype')} | {v.get('shape')} |" for k, v in feats.items()]
    lines += ["", f"State/action layout: `{provenance.get('state_layout')}`; hand frame: `{provenance.get('hand_frame')}`; task source: `{provenance.get('task_source')}`. See `meta/egosmith_provenance.json`.", ""]
    if payload.get("source_frames_index"):
        lines += ["## Rehydration", "", f"`{payload['source_frames_index']}` maps every episode to its source clip (clip name, media file name, fps, frame names). Extract those frames from the original data, then:", "",
                  "```", "python scripts/build/lerobot_rehydrate_video.py --labels_root <this dataset> --frames_root <frames> --output_dir <full dataset>", "```", ""]
    if spec.citation:
        lines += ["## Citation", "", "```", spec.citation.strip(), "```", ""]
    lines += ["## Loading", "", "```python", "from lerobot.datasets.lerobot_dataset import LeRobotDataset", f"ds = LeRobotDataset(repo_id=\"local/{_slug(name)}\", root=\"<this directory>\")", "```", ""]
    if spec.contact:
        lines += [f"Contact: {spec.contact}", ""]
    return "\n".join(lines)


__all__ = ["BUNDLED_LICENSE_DIR", "bundled_license_text", "KNOWN_LICENSES", "RELEASE_TIERS", "ReleaseSpec", "check_release_consistency", "release_spec_from_dict", "render_readme", "write_release_bundle"]
